[package]
name = "lemonade_model"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
serde = { version = "1.0.214", features = ["derive"] }
uuid = { version = "1.11.0", features = ["v7"] }
chrono = "0.4.38"
orion = "0.17.7"
snafu = "0.8.5"
