version: "3.0"

services:
  minecraft:
    build: .
    image: ghcr.io/mrlarssonjr/minecraft
    volumes:
      - minecraft:/minecraft
    ports:
      - "25565:25565"
    deploy:
      replicas: 1

volumes:
  minecraft:
